### ISSUE TITLE
프로젝트 셋업

### ISSUE THREAD

**Issue by mdgarden** [ZZIPSA/kkuk-kkuk-fe#1]
- [x] Next.js
- [x] App router
- [x] auth.js
- [x] shadcn
- [x] storybook
- [x] zustand
- [x] swr
- [x] tailwind

**Comment by 2chanhaeng** [comment]
Auth.js 는 Prisma 설정 이후 하겠습니다.

**Comment by mdgarden** [comment]
Auth.js와 Prisma 설정은 제가 하는 것으로 별도 이슈를 만들었습니다. #14 
다른 설정이 완료되었다면 확인 후 클로즈 부탁드리겠습니다.
