### ISSUE TITLE
회원탈퇴 모달창 레이아웃

### ISSUE THREAD

**Issue by 2chanhaeng** [ZZIPSA/kkuk-kkuk-fe#112]
### 작업 내용

회원탈퇴 모달창 레이아웃을 완성합니다.

<img width="422" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/b0a14123-49f1-45e6-9ab7-53e1c2678095">

**Comment by mdgarden** [comment]
에고 이거 코멘트가 늦었네요; 회원 탈퇴 기능은 MVP에 포함되지 않을 예정입니다. 번거로우시겠지만 피그마의 캘린더 자주 확인해가면서 작업 부탁드립니다!🙇‍♀️

**Comment by 2chanhaeng** [comment]
해결: #113
