### ISSUE TITLE
업로드한 키트 API 수정

### ISSUE THREAD

**Issue by 2chanhaeng** [ZZIPSA/kkuk-kkuk-fe#119]
### 기대한 동작

업로드한 키트 API `/api/my/kits?userId=${userId}`에서 자신이 업로드한 키트가 정상적으로 응답됩니다.

### 실제 동작

업로드한 키트 API `/api/my/kits?userId=${userId}`에서 자신이 업로드한 키트가 응답되지 않습니다.

### 재현 방법

`/api/my/kits?userId=${userId}` 를 요청합니다.

**Comment by 2chanhaeng** [comment]
`app/api/my/kits/route.ts` 내 GET 라우터를 `app/api/my/rallies/route.ts` 내 GET 처럼 URL 파라미터에서 사용자ID 를 가져오도록 수정하면 될 것 같습니다.

**Comment by mdgarden** [comment]
핫픽스로 대응하겠습니다.
