### ISSUE TITLE
[키트 상세 화면] 여백없음 / 브라우저에서 표시 비율의 문제 확인

### ISSUE THREAD

**Issue by mdgarden** [ZZIPSA/kkuk-kkuk-fe#125]
### 기대한 동작
키트 상세 화면에서 레이아웃대로 표시되어야 합니다.

### 실제 동작

PC
<img width="731" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/3a19afb8-f993-4240-a4be-6c8cf60d54bb">
모바일
<img width="463" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/6cdbdd52-3049-4b8c-aaf5-c4be76fc16b8">

- 썸네일 이미지와 제목~닉네임 사이에 여백이 없습니다.
- PC의 경우, 타이틀과 닉네임이 비율에 맞지않게 작은 것 같습니다.

### 재현 방법

- 크롬
- 파폭, 엣지는 확인하지 못했습니다.

**Comment by 2chanhaeng** [comment]
한 줄 짜리 수정이라 hotfix 로 수정했습니다. 2028100c949d064b1c72058aa93f7812d4db8c5a
<img width="490" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/00cbc52a-492c-443f-a2f5-9b6fc84a4cd0">
