### ISSUE TITLE
[나의 정보 화면] 회원탈퇴 기능에서 경고표시가 뜨지 않음

### ISSUE THREAD

**Issue by mdgarden** [ZZIPSA/kkuk-kkuk-fe#137]
### 기대한 동작

아래 모달에서 "탈퇴하기" 버튼을 눌렀을 때, alert으로 "준비 중인 기능입니다." 라는 문구가 표시되어야합니다.
<img width="715" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/bee3cd19-07fd-4135-bb12-c8458f02f474">

### 실제 동작

alert가 뜨지 않으며, 404페이지로 리다이렉트됩니다.

### 재현 방법

- 로그인 후, 나의 정보 수정 페이지 `my/settings/`로 이동합니다. 
- 회원탈퇴 버튼을 클릭하여 모달을 표시하고, "탈퇴하기" 버튼을 클릭합니다.

**Comment by 2chanhaeng** [comment]
이 기능에 대해 조금 의문점이 있는데
1. `준비 중인 기능입니다` 라는 안내문을 띄우는 게 UX에 좋은 영향을 주지 않을 것 같습니다. 아직 사용할 수 없는 기능이라면 사용자에게 보여주지 않는 것이 차라리 낫지 않을까요? 저희가 어차피 dev 브랜치도 만들어 놨으니 배포 브랜치에서는 해당 버튼 자체를 없애는 것이 나을 것 같습니다. 사족으로 이미 지나간 얘기지만 키트 페이지의 북마크, 좋아요 버튼에 대해서도 비슷한 생각을 했었습니다.
2. 회원탈퇴 자체를 불가능하게 한다면 앱 자체의 신뢰를 떨어트릴 것 같습니다. 최소한 `공식 연락처 이메일로 연락주세요` 라는 안내문을 추가하는 것이 좋다고 생각합니다.
