### ISSUE TITLE
[나의 정보 페이지] "탈퇴하기" 버튼을 눌렀을 때 alert이 뜨지 않음

### ISSUE THREAD

**Issue by mdgarden** [ZZIPSA/kkuk-kkuk-fe#156]
### 기대한 동작

나의 정보 페이지에서 "탈퇴하기" 버튼을 눌렀을 때, alert으로 "관리자에게 문의하기" 라는 문구가 떠야합니다.

### 실제 동작

404 페이지로 이동합니다.

### 재현 방법

나의 정보 페이지에서 탈퇴하기 버튼을 클릭합니다.

**Comment by 2chanhaeng** [comment]
디렉토리 구조가 #159 에서 변경됐기 때문에 #159 이후로 수정하겠습니다.

**Comment by 2chanhaeng** [comment]
#162 로 해결했습니다.
