### ISSUE TITLE
불필요한 페이지 삭제

### ISSUE THREAD

**Issue by mdgarden** [ZZIPSA/kkuk-kkuk-fe#158]
### 작업 내용

불필요한 페이지, 컴포넌트 등을 일괄적으로 삭제합니다.

### 삭제해야할 페이지

- [x] `app/upload/page.tsx`

**Comment by 2chanhaeng** [comment]
`app/upload/page.tsx` 은 #159 에서 제거했습니다. [참고](https://github.com/ZZIPSA/kkuk-kkuk-fe/pull/159#discussion_r1650391395)

**Comment by 2chanhaeng** [comment]
일단은 이슈를 닫아두겠습니다. 혹시 불필요한 코드가 추가로 발견될 경우 해당 이슈를 재오픈해주시면 감사하겠습니다.
