### ISSUE TITLE
[랠리 진행중 페이지] 마지막 리워드 스탬프 찍기 버튼에서 스탬프 아이콘의 색이 다름

### ISSUE THREAD

**Issue by mdgarden** [ZZIPSA/kkuk-kkuk-fe#160]
### 기대한 동작

마우스 호버했을 때, 스탬프 아이콘의 테두리 색이 버튼 색과 같아야합니다.

### 실제 동작

버튼색은 오렌지, 아이콘의 테두리 색은 보라색으로 표시됩니다.
*의도된 내용이라면 클로즈해주세요.

호버전 
<img width="176" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/9ae9581d-9e55-4b5d-bc0c-bdf15ba709e0">
호버후
<img width="171" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/a72f05af-1a73-4eaa-88e1-6250e97a56ae">

### 재현 방법

스탬프가 5개 찍혀있는 상태의 랠리 진행중 페이지에 접속해서, 스탬프 찍기 버튼에 마우스 호버합니다.

**Comment by 2chanhaeng** [comment]
디렉토리 구조 변경으로 인해 #159 완료 후 처리하겠습니다.

**Comment by 2chanhaeng** [comment]
#162 로 해결했습니다.
