### ISSUE TITLE
[랠리 완료 페이지] 완주 성공 버튼이 잘 보이지 않음

### ISSUE THREAD

**Issue by mdgarden** [ZZIPSA/kkuk-kkuk-fe#161]
버그는 아닌데, "스탬프 랠리 완주 성공!"이라는 버튼이 너무 흐릿해서 잘 안보입니다...ㅠ
일단 기록용으로 스크린샷만 남겨놓겠습니다.

<img width="752" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/fee7fa5a-50f9-4f18-9444-558d62cd1eaf">

**Comment by 2chanhaeng** [comment]
디렉토리 구조 변경으로 인해 #159 완료 후 처리하겠습니다.

**Comment by 2chanhaeng** [comment]
#162 로 해결했습니다.
