### ISSUE TITLE
[글로벌 헤더]헤더 바의 화살표가 양끝단에 있음

### ISSUE THREAD

**Issue by mdgarden** [ZZIPSA/kkuk-kkuk-fe#179]
### 기대한 동작

다른 헤더와 마찬가지로 화살표의 폭이 맞아야합니다.

### 실제 동작
화살표가 화면 끝에 가있습니다.
<img width="1437" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/ef3e86d2-1503-43e7-9ffb-cea4ddd33617">

### 재현 방법

키트 상세 화면등에 접속합니다.

**Comment by 2chanhaeng** [comment]
큰 변경이 필요 없어서 hotfix 로 처리했습니다. 9988f57e1c44f640bdcd1b2fdc870a89c8ea9880

**Comment by 2chanhaeng** [comment]
큰 변경이 필요 없어서 hotfix 로 처리했습니다. 9988f57e1c44f640bdcd1b2fdc870a89c8ea9880
