### ISSUE TITLE
MVP Pages 생성

### ISSUE THREAD

**Issue by 2chanhaeng** [ZZIPSA/kkuk-kkuk-fe#2]
### 작업할 내용

- [x] `/`: 루트 페이지(전체 키트 조회)
- [x] `/kits`
  - [x] `/[kitId]`: 특정 키트 페이지
    - [x] `/start`: 특정 키트를 통해 랠리 생성 페이지
- [x] `/my`: 나의 정보
  - [x] layout
  - [x] `/joined`: 참가 중인 랠리 페이지
  - [x] `/completed`: 완료한 랠리 페이지
  - [x] `/created`: 생성한 키트 페이지
  - [x] `/settings`: 개인 정보 수정 페이지
- [x] `/upload`: 키트 생성 관련
  - [x] `/input`: 키트 생성 페이지 페이지
  - [x] `/confirm`: 키트 생성 확인 페이지

### 추가 내용

- `/` = 전체 키트 조회 페이지: `/kits` 를 전체 키트 조회 페이지로 만들고 `/` 로 접속하면 지금은 `/kits` 로 리다이렉트 시켰다가 MVP 완성되면 소개 페이지로 만드는 게 나을 것 같습니다.
- `/upload/input`: `/kits/upload` 가 키트 생성, `/kits/upload/confirm`가 키트 생성 확인 페이지인게 낫지 않을까요?

**Comment by 2chanhaeng** [comment]
@blissful-y0 현재까지 MVP에 작성된 페이지 모두 생성 완료했습니다.

**Comment by blissful-y0** [comment]
> ### 작업할 내용
> * [x]  `/`: 루트 페이지(전체 키트 조회)
> * [x]  `/kits`
>   
>   * [x]  `/[kitId]`: 특정 키트 페이지
>     
>     * [x]  `/start`: 특정 키트를 통해 랠리 생성 페이지
> * [x]  `/my`: 나의 정보
>   
>   * [x]  layout
>   * [x]  `/joined`: 참가 중인 랠리 페이지
>   * [x]  `/completed`: 완료한 랠리 페이지
>   * [x]  `/created`: 생성한 키트 페이지
>   * [x]  `/settings`: 개인 정보 수정 페이지
> * [x]  `/upload`: 키트 생성 관련
>   
>   * [x]  `/input`: 키트 생성 페이지 페이지
>   * [x]  `/confirm`: 키트 생성 확인 페이지
> 
> ### 추가 내용
> * `/` = 전체 키트 조회 페이지: `/kits` 를 전체 키트 조회 페이지로 만들고 `/` 로 접속하면 지금은 `/kits` 로 리다이렉트 시켰다가 MVP 완성되면 소개 페이지로 만드는 게 나을 것 같습니다.

이견 없습니다.

> * `/upload/input`: `/kits/upload` 가 키트 생성, `/kits/upload/confirm`가 키트 생성 확인 페이지인게 낫지 않을까요?

upload, confirm 등의 언어는 유저보다는 개발자 친화적인 단어 같습니다. 라우터 이름은 페이지 기능을 명확하게 이해할 수 있는 게 더 좋을 것 같습니다.
따라서
- 키트 전체 조회 페이지명: /kits
- 키트 등록 페이지 이름: /kit/new (번개장터 참고)
- 키트 생성 확인: 생성 확인 페이지가 별도로 있는 것보다는 바로 해당 키트의 디테일 페이지(kit/:id)로 이동하는 것이 낫겠습니다 (논의필요)
