### ISSUE TITLE
프리즈마 + Next.js 구현에 필요한 기능 정리

### ISSUE THREAD

**Issue by mdgarden** [ZZIPSA/kkuk-kkuk-fe#20]
### 작업 내용

프리즈마와 Next.js로 API를 구현하면서 필요한 기능들을 정리하고 적용합니다.

### 상세 내용

- [ ] #44
- [x] ~~find구문에서 기본적으로 `{where: {deletedAt:null}}`이 적용되게 합니다.~~
 조사는 완료했으나 소프트 딜리트에 대한 스펙 합의가 필요하므로 적용은 하지 않습니다.
- [x] 각 API마다 달라지는 response값과 reqeust값에 대한 타입을 효과적으로 관리할 수 있게 합니다.
- [x] prisma + Next.js 14 + App 라우터의 일반적인 컨벤션을 익히고 적용합니다.

### 확인 내용

- [x] 프론트에서 직접적으로 "@Prisma/client' 를 사용하지 않게 합니다.
- [x] 모든 모델을 작성하고, 다른 분들이 타입을 유연하게 작성할 수 있도록 예시를 작성합니다.
- [x] 현재 작성되어있는 프론트 페이지에 타입을 적용합니다.

### 기타

이 작업은 다음 카테고리의 API 작업을 시작하기 전에 선행하여 진행하고, 기존의 랠리 API에 대해 적용하고 검증을 거친 후 프로젝트에 적용할 예정입니다.

**Comment by mdgarden** [comment]
- 데이터 유효성 검사
  - zod와 joi가 있는데 zod가 좀 더 많이 쓰이는 듯
  - https://zod.dev/

- 파이프
  - Next.js의 파이프가 따로있음
  - https://next-api-decorators.vercel.app/docs/pipes

- 디렉토리 구조
  - 지금처럼 API로 분리해서 사용하는 경우도 있지만 굳이 API가 아니어도 되는 로직은 `actions`라는 파일로 따로 정리하는 경우도 있음
  - [참고1](https://github.com/moinulmoin/chadnext/blob/0813925235a952f467478f89dc75ca780784eeb6/src/app/%5Blocale%5D/dashboard/settings/actions.ts)
  - [참고2](https://github.com/fajarwz/blog-nextjs-crud/blob/master/src/app/actions/posts.ts)

**Comment by mdgarden** [comment]
타입 관리에 대해서 GPT가 제시해준 예시

모델에 대한 CRUD타입도 prisma에서 자동 생성해준다고 함

```ts
import { z } from 'zod';
import { Prisma } from '@prisma/client';

// Prisma에서 생성된 타입을 가져오기
export type Post = Prisma.Post;
export type PostCreateInput = Prisma.PostCreateInput;
export type PostUpdateInput = Prisma.PostUpdateInput;

// zod를 사용해 유효성 검사 스키마 정의
export const PostSchema = z.object({
  title: z.string().min(1, "Title is required"),
  content: z.string().optional(),
  published: z.boolean().default(false)
});

// 클라이언트와 서버 간의 데이터 포맷을 위해 추가적인 타입 정의
export type PostResponse = z.infer<typeof PostSchema> & {
  id: number;
  createdAt: Date;
};
```

**Comment by mdgarden** [comment]
미들웨어를 적용하여 모든 반환값에 대하여 기본적으로 `{where: {deletedAt:null}}`와 `deletedAt` 항목을 제외하고 반환하도록 함


```ts
// 미들웨어 예시
import { Prisma } from '@prisma/client';

const softDeleteMiddleware: Prisma.Middleware = async (params, next) => {
  if (params.action === 'findMany' || params.action === 'findFirst' || params.action === 'findUnique') {
    // Ensure we're querying only non-deleted records
    if (!params.args) {
      params.args = {};
    }
    if (!params.args.where) {
      params.args.where = {};
    }
    params.args.where.deletedAt = null;
  }

  // Call the next middleware or resolver
  const result = await next(params);

  // Remove the `deletedAt` field from the result
  if (Array.isArray(result)) {
    result.forEach((item) => {
      if (item.deletedAt !== undefined) {
        delete item.deletedAt;
      }
    });
  } else {
    if (result && result.deletedAt !== undefined) {
      delete result.deletedAt;
    }
  }

  return result;
};

export default softDeleteMiddleware;
```

```ts
// 미들웨어 적용방법
import { PrismaClient } from '@prisma/client';
import softDeleteMiddleware from './middleware';

const prisma = new PrismaClient();

prisma.$use(softDeleteMiddleware);

export default prisma;
```

**Comment by 2chanhaeng** [comment]
> zod와 joi가 있는데 zod가 좀 더 많이 쓰이는 듯

`zod`는 지금 프로젝트에도 설치되어 있습니다. 바로 사용하실 수 있어요.

> 지금처럼 API로 분리해서 사용하는 경우도 있지만 굳이 API가 아니어도 되는 로직은 `actions`라는 파일로 따로 정리하는 경우도 있음

[Server Action](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations) 문서 참고해보시면 좋을 듯 합니다.

**Comment by mdgarden** [comment]
코멘트 감사합니다!
> zod는 지금 프로젝트에도 설치되어 있습니다. 바로 사용하실 수 있어요.

프론트에서 이미 사용 중이신가요? `form`같은건 프론트에서 바로 검증하는 방법도 있던 것 같은데, 프론트에서 사용 중이시라면 어디서 어떻게 사용하고 있는지 궁금합니다.

> [Server Action](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations) 문서 참고해보시면 좋을 듯 합니다.

이 문제는 구체적인 구현방법보다는 구조적인 면에서 고민하고 있습니다. `actions`로 구분해서 사용하게 되었을 때, 다음과 같은 측면에서 우려사항이 있어서 공유합니다.

### 검토 내용
#### 전제사항
- 현재 우리 앱은 향후 백엔드 분리가 확정되어 있는 상황입니다.
- 따라서 가능하면 프론트와의 결합도를 낮추고 싶습니다.
  - 백엔드 분리를 했을 때, 프론트에서 필요한 수정을 최소한이 될 수 있도록 지금 단계에서부터 생각하며 진행하고 싶습니다.
  - 백엔드 측면에서도 크게 생각하지않고 API만 그대로 옮겨올 수 있도록 작업 과정을 최소화 하고 싶습니다.
 - 백엔드 측면에서는 Next.js의 기능을 최대한 활용하는 것에 목표를 두고 있지 않습니다.
   - Next.js에서 통합 개발하기로 결정되었기 때문에 어느정도 컨벤션을 따르는 것은 맞으나, 완전한 Next.js의 앱을 만들기보다는 효과적인 타입관리와 빠른 API 명세서의 공유 등을 이점으로 가져가고 싶습니다.
   - 가능하면 기본적인 룰만 지키는 방향으로 API를 구현하고 싶습니다.

#### `actions`로 분리했을 때
- `actions`로 분리해서 사용하면, 프론트에서는 API 요청과 DB에서 직접 가져오는 액션 이렇게 두가지의 방법으로 데이터를 가져오게 됩니다. 아직 프로젝트 규모가 작고 API와 action의 구분이 어렵지는 않으나 백엔드 분리 후에는 결국 action은 전부 API 요청으로 바뀌게 됩니다.
- 개인적인 이유로는 `actions`로 분리해서 사용하는 경우, Next.js의 컨벤션이라는 것 이외의 이점이 잘 보이지 않습니다.

**Comment by mdgarden** [comment]
- 에러메세지
  - 작업량이 많아질 것 같아 별도의 이슈로 분리했습니다.
- deleteAt 기본 설정
  - 소프트 딜리트와 cascade에 대한 합의가 필요하므로 이번 이슈에서는 방법만 확인하고 적용은 하지 않겠습니다.
- `actions`
  - 현재 우리 프로젝트와 맞지않는 점이 많아 적용하지 않겠습니다.
- 이번 이슈는 타입 위주로 정리하고 적용합니다.
  - 프론트에서 사용하는 타입과 백엔드에서 사용하는 타입을 구분합니다.
  - 프론트에서 사용하는 타입은 프리즈마와 결합도를 낮추는 방향으로 디렉토리와 파일을 작성합니다.
    - 1차적으로 `model`이라는 폴더를 만든 후, 프론트용 모델을 작성합니다.
