### ISSUE TITLE
Auth.js vs NextAuth

### ISSUE THREAD

**Issue by mdgarden** [ZZIPSA/kkuk-kkuk-fe#23]
### 작업 내용

Auth.js와 NextAuth에 대해서 조사하고 어떻게 로그인을 구현할지 결정합니다.

### 상세 내용

[공식문서](https://authjs.dev/getting-started/authentication/oauth)에 따르면 Auth.js로 사용해도 NextAuth를 사용해야하는데, NextAuth만으로 트위터 로그인 구현이 가능한지 확인합니다. 현재 Auth.js 내용을 정확하게 파악하고 있지 않으므로 이 이슈 자체가 무효일 가능성도 있습니다.
Auth.js와 NextAuth의 장단점과 구현 방법의 차이를 살펴 로그인의 구현 방법을 결정합니다.

**Comment by 2chanhaeng** [comment]
Next.js + Prisma + Auth.js 로 트위터 로그인 구현 방법은 [제 블로그 글](https://chomu.dev/posts/2024/05/03/Auth.js,%20Prisma%20%EA%B7%B8%EB%A6%AC%EA%B3%A0%20Twitter%20OAuth%EC%9D%98%20%EC%9D%B8%EC%A6%9D)을 참고해보시면 좋을 듯 합니다. ~~못생긴 건 이해 부탁 드립니다 아직 만드는 중 + 디자인 감각이 부족해서ㅠㅠ~~
차이점에 대해서는 정리 후 차차 올리겠습니다.

**Comment by 2chanhaeng** [comment]
Auth.js(NextAuth@5.0.0^) 의 가장 큰 차이점은 [`auth`](https://authjs.dev/getting-started/migrating-to-v5#authentication-methods) 입니다. 맥락에 맞춰 알맞게 가져와 사용해야만 했던 이전 버전과 달리 5.0 부터는 서버 내 인증은 모두 `auth` 로 통합되었습니다. 뿐만 아니라 이전 버전에서는 Route Handlers 와 API 라우트 (Edge) 에서는 인증이 불가능 했습니다. 5.0 부터는 `auth` 를 통해 인증을 진행할 수 있습니다.

|사용처|v4|v5|
|---|---|---|
|[Server Component](https://nextjs.org/docs/app/building-your-application/rendering/server-components)|`getServerSession(authOptions)`|`auth()` 호출|
|[Middleware](https://nextjs.org/docs/app/building-your-application/routing/middleware)|`withAuth(middleware, subset of authOptions) 래퍼`|`auth` export / `auth()` 래퍼|
|[Route Handler](https://nextjs.org/docs/app/building-your-application/routing/route-handlers)|지원하지 않음|`auth()` 래퍼|
|API 라우트 (Edge)|지원하지 않음|`auth()` 래퍼|
|API 라우트 (Node.js)|`getServerSession(req, res, authOptions)`|`auth(req, res)` 호출|
|API 라우트 (Node.js)|`getToken(req)` (세션 로테이션 없음)|`auth(req, res)` 호출|
|[`getServerSideProps`](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props)|`getServerSession(ctx.req, ctx.res, authOptions)`|`auth(ctx)` 호출|
|[`getServerSideProps`](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props)|`getToken(ctx.req)` (세션 로테이션 없음)|`auth(req, res)`|

사용법에 대한 차이는 [공식 문서](https://authjs.dev/getting-started/migrating-to-v5#details)를 참고해주세요.

**Comment by 2chanhaeng** [comment]
그 외에도
- App Router 선지원(Pages 도 지원하긴 함)
- [개발용 배포에서도 사용 가능](https://authjs.dev/getting-started/deployment#securing-a-preview-deployment)
- 설정 간편화 (config 공유, [env 환경 변수 추정](https://authjs.dev/guides/environment-variables#environment-variable-inference) 등)
- OAuth 제공자에 [`account()`](https://authjs.dev/reference/core/providers#account) 콜백 지정 가능
- Edge 지원

Auth.js는 이제 @auth/core를 기반으로 더 엄격한 OAuth/OIDC 사양을 준수하며 빌드되므로 일부 기존 OAuth 공급업체가 중단될 수 있습니다. 자세한 내용은 미해결 이슈를 참조하세요.
OAuth 1.0 지원은 더 이상 사용되지 않습니다.
이제 필요한 최소 Next.js 버전은 14.0입니다.
next-auth/next 가져오기가 대체되었습니다. 자세한 내용은 서버 측 인증하기를 참조하세요.
다음 인증/미들웨어 가져오기가 대체되었습니다. 자세한 내용은 서버 측 인증하기를 참조하세요.
- 엄격한 OAuth/OIDC 사양 준수, OAuth 1.0 지원 제외로 인한 일부 Provider 사용 불가
- Next.js@14^ 지원
    The import next-auth/next is replaced. See [Authenticating server-side](https://authjs.dev/getting-started/migrating-to-v5#authenticating-server-side) for more details.
    The import next-auth/middleware is replaced. See [Authenticating server-side](https://authjs.dev/getting-started/migrating-to-v5#authenticating-server-side) for more details.

**Comment by mdgarden** [comment]
정리감사합니다! 구현할 때 참고하겠습니다.
해당 이슈는 내용이 완결되었으므로 담당자를 저로 바꾸고, 로그인 구현 작업 시작할 때 클로즈하겠습니다.

**Comment by mdgarden** [comment]
### 트위터 로그인 1.0과 2.0 비교

특징 | OAuth 1.0a | OAuth 2.0
-- | -- | --
보안 방식 | 서명 기반 (signature) | 토큰 기반 (token)
토큰 | Access Token, Access Token Secret | Access Token (Bearer Token)
요청 흐름 | 복잡한 서명 및 토큰 교환 | 간단한 Authorization Code, Implicit Grant 등
API 지원 | 트위터 API 초기 버전 | 트위터 API v2
장점 | 요청 무결성 보장, 높은 보안성 | 구현 간편, 유연성 높음
단점 | 복잡한 설정 및 서명 처리 | 토큰 탈취에 대한 보안 위협 존재

그 외 : 2.0에서는 email 취득 불가

개인적으로 생각하는 1.0, 2.0의 가장 큰 차이는 로그인 화면
아직 2.0 로그인 화면을 본 적이 없음
![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/817a231e-48ce-4a1f-874b-df399cbb3c20)
![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/07f88086-f652-4bdf-a984-f5e663678355)
