### ISSUE TITLE
타입 정의 파일 제거로 인한 오류

### ISSUE THREAD

**Issue by 2chanhaeng** [ZZIPSA/kkuk-kkuk-fe#26]
### 기대한 동작

모델에 대한 타입을 문제 없이 사용할 수 있어야 합니다.

### 실제 동작

일부 파일에서 사용하던 타입 정의가 사라졌습니다.

### 재현 방법

pull e30f65529fab100a0bcac83c4b6daf1fade0cb69

### 원인

#19 에서 [`@/types`](https://github.com/ZZIPSA/kkuk-kkuk-fe/tree/7aa13a19ba19be996c849f468cd9a0a9f38114be/types)의 파일들이 제거되면서 타입 정의가 제거되었습니다.

### 해결

b3430d78f3cfb26afa2389c8d480fcabb65d061c `@prisma/client` 에 정의되어 있는 타입을 사용해 타입을 재정의했습니다. 
1f60d8e07a361bb823c021a4b8e4720f6a892238 덕분에 타입이 더 명확해져 Nullable한 일부 값이 누락될 경우를 대비해 기본 값을 정의하여 표시하도록 만들었습니다. 
122170f89389b72ab3e7f1e86ce70ac98247864e 추가적으로 `@/lib/prisma/selects.ts` 값들의 타입을 `satisfied` 키워드를 사용해 명확한 타입 추론이 되도록 만들었습니다.

**Comment by mdgarden** [comment]
프론트에서 사용하는 타입은 별도로 사용하는 줄 알고 삭제했습니다.🙇‍♀️
번거롭게 해드려서 죄송합니다. 이 부분에 대한건 이번주 회고 시간에 대해서 얘기해볼게요.
#27 을 확인하니 이 티켓도 초무님이 가져가신 것 같은데, 프로젝트 설정과 담당자 어사인 부탁드립니다.🙇‍♀️

**Comment by 2chanhaeng** [comment]
#31 으로 해결
