### ISSUE TITLE
로그 설정

### ISSUE THREAD

**Issue by mdgarden** [ZZIPSA/kkuk-kkuk-fe#36]
### 작업 내용

유저의 유입 경로, 조회수 등 방문 기록을 확인할 수 있는 로그를 설정합니다.

### 상세 내용

작업 착수 시 상세 내용 작성하겠습니다.

- [ ] 작업내용1
- [ ] 작업내용2

### 테스트 내용

- [ ] 테스트내용1
- [ ] 테스트내용2

**Comment by blissful-y0** [comment]
마당님 해당 작업은 어떻게 진행하실 예정인가요?
간단하게 GA를 사용해서 합의된 이벤트 로그들 수집하면 좋을거같습니다

**Comment by mdgarden** [comment]
로그 관련 작업은 해본적이 없어서 배경지식이 거의 없습니다...!
GA라면 Google Analytics말씀이 맞으시죠? 업무로 프로젝트에 적용해보기만 하고 실제로 로그가 어떻게 관리되는지는 본 적이 없어서 개인적으로 더 공부해볼려고 합니다 ㅠ 혹시 사용경험이 있으시다면 경험 공유 부탁드려요!

**Comment by mdgarden** [comment]
회의에서 얘기나왔던대로 담당자 변경했습니다! 잘 부탁드립니당!
