### ISSUE TITLE
키트 생성 페이지 스탬프 이미지 업로드 섹션

### ISSUE THREAD

**Issue by 2chanhaeng** [ZZIPSA/kkuk-kkuk-fe#42]
### 작업 내용

키트 생성 페이지 `/kits/new` 스탬프 이미지 업로드 섹션을 완성합니다.

### 상세 내용

- [x] #82
- [x] #131
- [x] API

### 테스트 내용

- [x] 키트 생성 페이지에서 타입 문제 없이 이미지가 업로드됩니다.

### 기타

기존 작업은 [issue/7](https://github.com/ZZIPSA/kkuk-kkuk-fe/tree/issue/7) 에서 확인하실 수 있습니다.

**Comment by mdgarden** [comment]
키트 생성 페이지 레이아웃은 완성되어있는 상태인가요? 우선 form 태그로 간단하게나마 레이아웃만 구현하는 이슈를 별도 작성하여 선행하는 것이 좋을 것 같습니다.

**Comment by mdgarden** [comment]
#131 과 중복인지 확인 후 클로즈 검토 부탁드립니다.
