### ISSUE TITLE
키트 생성 페이지 태그 입력

### ISSUE THREAD

**Issue by 2chanhaeng** [ZZIPSA/kkuk-kkuk-fe#43]
### 작업 내용

키트 생성 페이지 `/kits/new` 스탬프 태그 입력 섹션을 완성합니다.

### 테스트 내용

- [x] 키트 생성 페이지에서 타입 문제 없이 태그가 입력됩니다.

### 기타

기존 작업은 [issue/7](https://github.com/ZZIPSA/kkuk-kkuk-fe/tree/issue/7) 에서 확인하실 수 있습니다.

**Comment by mdgarden** [comment]
MVP에서 태그 사양을 변경하고 싶습니다.
- 키트 생성 화면에서, 태그 편집 기능을 넣지 않습니다. 태그를 변경해야할 경우, 해당 태그를 삭제하고 다시 입력해야합니다. 태그에 있는 연필 모양 아이콘도 삭제됩니다.
- 전체 키트 조회, 단일 키트 조회에서 태그가 클릭되지 않게 합니다.

태그 또한 우리 앱에서 중요한 기능이나, DB에 쌓여있는 키트가 많지 않을 때는 영향력이 적다는 점을 고려하여 태그 관련 기능은 다음 페이즈로 빼겠습니다.
