### ISSUE TITLE
폭이 좁은 화면에서 태그가 두 줄이 되는 현상

### ISSUE THREAD

**Issue by mdgarden** [ZZIPSA/kkuk-kkuk-fe#47]
### 기대한 동작

태그의 길이나 화면 폭과 상관없이 태그가 한 줄로 표시되어야 합니다.

### 실제 동작

모바일 등 화면의 폭이 좁아졌을 때 태그가 두 줄이 되는 경우가 발생합니다. 태그의 가로 스크롤은 정상적으로 가능합니다.
![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/03dc2630-022c-4ac9-91dd-d1001cfb26a7)

### 재현 방법

브라우저: 화면의 폭을 줄입니다.
모바일: 개발자 도구에서 여러 기종을 선택하여 화면의 폭이 좁아지도록 합니다. (기종 무관)

브라우저의 화면 폭을 줄였을 경우
![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/7d13e379-3fbb-4db7-a6ab-e41f1e24c03c)

**Comment by 2chanhaeng** [comment]
확인 결과 크롬에서 한글로 시작하는 태그에서 CJK로 시작하는 태그에서 발생하는 것 같습니다.
