### ISSUE TITLE
이미지가 깨져보이는 현상

### ISSUE THREAD

**Issue by mdgarden** [ZZIPSA/kkuk-kkuk-fe#58]
### 기대한 동작

/kits 페이지에서, 각 키트의 썸네일 이미지가 해상도에 맞게 보여야합니다.

### 실제 동작

실제 이미지의 해상도와 관계 없이 썸네일 이미지의 화질이 대폭 낮아져있습니다.

### 재현 방법

/kits 페이지로 접속합니다. 기종은 무관합니다.

![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/39ffe355-81de-4181-86a3-fe90d3584d93)

*가장 마지막에 있는 테스트용 이미지 원본
(저애,,,프세카최애칭구들임니다,,,,,머슥)
사이즈 : 644x478
용량 : 360kb
![EcnRAuYU0AEUOep](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/16d28f21-b29a-4f2a-b696-280b7a1efeba)

**Comment by 2chanhaeng** [comment]
아직 확실하진 않지만 Next.js 의 [이미지 최적화](https://nextjs.org/docs/app/building-your-application/optimizing/images) 때문이 아닐까 싶습니다.
[관련 영상(1분 21초부터)](https://youtu.be/IU_qq_c_lKA?t=81)
