### ISSUE TITLE
키트 생성 페이지

### ISSUE THREAD

**Issue by 2chanhaeng** [ZZIPSA/kkuk-kkuk-fe#7]
### 작업할 내용

키트 생성 페이지 `/kits/new`

### 상세 내용

- [ ] #42
- [ ] 제목
- [ ] #43
- [ ] 설명

### 테스트 내용

MVP 참고

### 기타

스탬프 이미지 업로드 필드를 MVP를 따라 여섯개의 태그로 나누려고 합니다. 그런데 ref 를 사용하다보니 해결방법을 잘 모르겠습니다.

**Comment by mdgarden** [comment]
해당 내용을 확인한 결과, 여기에 커밋해주신 내용은 이미 main 브랜치에 병합되어있는 것으로 보입니다.
이미지 업로드와 태그외에는 어느정도 틀이 잡혀있으므로 우선은 이 이슈를 클로즈해주시고, 이미지 업로드와 태그 입력을 완성을 목표하는 두 개의 이슈를 별도로 작성해주세요.

**Comment by 2chanhaeng** [comment]
#42 #43 으로 분리했습니다.
