### ISSUE TITLE
Kit 전체 조회 페이지

### ISSUE THREAD

**Issue by 2chanhaeng** [ZZIPSA/kkuk-kkuk-fe#8]
### 작업할 내용

`/kits` Kits 전체 조회 페이지

**Comment by mdgarden** [comment]
추후 작업 시작전에 담당자를 다시 선택합니다.

**Comment by 2chanhaeng** [comment]
#17 병합으로 해결

**Comment by 2chanhaeng** [comment]
https://github.com/ZZIPSA/kkuk-kkuk-fe/pull/17 병합으로 해결
