### ISSUE TITLE
[전체 키트 조회 화면] 크롬 화면에서 레이아웃이 무너짐

### ISSUE THREAD

**Issue by mdgarden** [ZZIPSA/kkuk-kkuk-fe#99]
### 기대한 동작
- 대상 페이지 : `/kits`
모바일 화면에서 피그마에 작성되어 있는대로 디자인 레이아웃이 표시되어야합니다.

### 실제 동작
~~화면 폭이 좁아졌을 경우~~ 크롬에서 키트를 표시하는 카드에서 레이아웃이 무너집니다. 화면 폭과 관계 없이 발생합니다.
- 키트의 대표이미지가 정사각형으로 표시되지 않습니다.
- 키트 업로더의 닉네임과 태그 사이에 지나치게 많은 공백이 있습니다.

### 재현 방법

- 크롬, iPhone SE
![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/c70cd9d6-b43f-4239-9d07-00e41e0122fa)
- 크롬, iPhone 12 Pro
![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/f2947752-9627-4f49-b78d-f51bb3c94128)

**Comment by mdgarden** [comment]
추가 확인)
파이어폭스에서는 이 현상이 발생하지않습니다.
Edge에서는 발생합니다.

**Comment by 2chanhaeng** [comment]
hotfix 로 해결했습니다. 3ff6847ce31308ec1094f8259dff164c7f516834
![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/548d1bca-4cfe-4622-aff3-312bbb149bf9)
